{% set name = "sqlalchemy-heavyai" %}
{% set version = "1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sqlalchemy-heavyai-{{ version }}.tar.gz
  sha256: dc54a58aaa76d8063d6193baa9706754b32df7d5caf88690a8af5ac22dc45df5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - flit-core >=3.3,<4
  run:
    - heavyai
    - importlib_metadata
    - python >={{ python_min }}
    - sqlalchemy

test:
  imports:
    - sqlalchemy_heavyai
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/sqlalchemy-heavyai/
  summary: HeavyAI SQLAlchemy Driver
  dev_url: https://github.com/heavyai/sqlalchemy-heavyai
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - tupui
    - pearu
    - andrewseidl
    - cdessanti
